const actives = new Map([[1, 'AUDCAD']
[1, 'AUDCHF']
[1, 'AUDJPY']
[1, 'AUDNZD']
[1, 'AUDUSD']
[1, 'CADCHF']
[1, 'EURGBP']
[1, 'EURJPY']
[1, 'EURUSD']
[1, 'GBPAUD']
[1, 'GBPCAD']
[1, 'GBPCHF']
[1, 'GBPJPY']
[1, 'GBPNZD']
[1, 'GBPUSD']
[1, 'NZDUSD']
[1, 'USDCAD']
[1, 'USDCHF']
[1, 'USDJPY']
[1, 'USDNOK']
])